services:
  db:
    image: postgres
    container_name: postgres_chatdb
    ports:
      - "5432:5432"
    volumes:
      - chat-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chatdb
      POSTGRES_PASSWORD: chatdb
      POSTGRES_DB: chatdb
    shm_size: 128mb
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer_chatdb
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  chat-db:
